### ISSUE TITLE
Error in running the script

### ISSUE THREAD

**Issue by wescravn** [litwi1rm/craigslist-to-osclass#2]
Traceback (most recent call last):
  File "./xmlMaker.py", line 53, in <module>
    ET.SubElement(listing, "content", lang="en_US").text = content + '\n\n' +row[0]
NameError: name 'content' is not defined

**Comment by Litwilly** [comment]
can you provide the csv your using? Its been many months since I've run this hoping something didn't change on craigslist to break this.

**Comment by wescravn** [comment]
Ryan,

Hi. I just used the default csv you had on the site initially, and got the
error on GitHub. I created my own csv as well, which is attached, but I get
a different error.

Traceback (most recent call last):

  File "./xmlMaker.py", line 24, in <module>

    region = pex.search(row[0]).groups()[0]

AttributeError: 'NoneType' object has no attribute 'groups'

**Comment by interbiznw** [comment]
@wescravn  did you ever figure it out? Getting this error now

**Comment by RamiJaloudi** [comment]
getting this error:

```
**Traceback (most recent call last):
  File "C:\Users\RJ\OneDrive\AND_LIST\craigslist-to-osclass-master\xmlMaker.py", line 53, in <module>
    ET.SubElement(listing, "content", lang="en_US").text = content + '\n\n' +row[0]
NameError: name 'content' is not defined**
```
